# Generated by Django 3.2.13 on 2022-04-27 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_type', models.CharField(choices=[('PD', 'Product discount'), ('SD', 'Set discount'), ('BD', 'Basket discount')], default='PD', help_text='Discount type', max_length=2, verbose_name='discount type')),
                ('discount_mechanism', models.CharField(choices=[('P', 'Percent discount'), ('S', 'Discount sum'), ('F', 'Fix price')], default='P', help_text='Discount mechanism', max_length=1, verbose_name='discount mechanism')),
                ('discount_value', models.PositiveIntegerField(default=0, help_text='Discount value', verbose_name='discount value')),
                ('is_active', models.BooleanField(default=True, help_text='There is active discount', verbose_name='is active')),
                ('description', models.TextField(help_text='Discount description', max_length=1000, verbose_name='description')),
                ('start_at', models.DateTimeField(help_text='Discount start date', verbose_name='start at')),
                ('finish_at', models.DateTimeField(help_text='Discount finish date', verbose_name='finish at')),
            ],
            options={
                'verbose_name': 'discount',
                'verbose_name_plural': 'discounts',
            },
        ),
        migrations.CreateModel(
            name='SetDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id_1', models.ManyToManyField(blank=True, default='', help_text='Category(ies) 1 id', related_name='set_discount_1', to='product.Category', verbose_name='category(ies) 1 id')),
                ('category_id_2', models.ManyToManyField(blank=True, default='', help_text='Category(ies) 2 id', related_name='set_discount_2', to='product.Category', verbose_name='category(ies) 2 id')),
                ('discount_id', models.ForeignKey(help_text='Discount id', on_delete=django.db.models.deletion.CASCADE, related_name='set_discount', to='discount.discount', verbose_name='discount id')),
                ('product_id_1', models.ManyToManyField(blank=True, default='', help_text='Product(s) 1 id', related_name='set_discount_1', to='product.Product', verbose_name='product(s) 1 id')),
                ('product_id_2', models.ManyToManyField(blank=True, default='', help_text='Product(s) 2 id', related_name='set_discount_2', to='product.Product', verbose_name='product(s) 2 id')),
            ],
            options={
                'verbose_name': 'set discount',
                'verbose_name_plural': 'set discounts',
            },
        ),
        migrations.CreateModel(
            name='ProductDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.ManyToManyField(blank=True, default='', help_text='Category(ies) id', related_name='product_discount', to='product.Category', verbose_name='category(ies) id')),
                ('discount_id', models.ForeignKey(help_text='Discount id', on_delete=django.db.models.deletion.CASCADE, related_name='product_discount', to='discount.discount', verbose_name='discount id')),
                ('product_id', models.ManyToManyField(blank=True, default='', help_text='Product(s) id', related_name='product_discount', to='product.Product', verbose_name='product(s) id')),
            ],
            options={
                'verbose_name': 'product discount',
                'verbose_name_plural': 'product discounts',
            },
        ),
        migrations.CreateModel(
            name='BasketDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_products_count', models.PositiveIntegerField(default=0, help_text='Minimum products count', verbose_name='minimum products count')),
                ('max_products_count', models.PositiveIntegerField(default=0, help_text='Maximum products count', verbose_name='maximum products count')),
                ('min_basket_cost', models.PositiveIntegerField(default=0, help_text='Minimum basket cost', verbose_name='minimum basket cost')),
                ('max_basket_cost', models.PositiveIntegerField(default=0, help_text='Maximum basket cost', verbose_name='maximum basket cost')),
                ('discount_id', models.ForeignKey(help_text='Discount id', on_delete=django.db.models.deletion.CASCADE, related_name='basket_discount', to='discount.discount', verbose_name='discount id')),
            ],
            options={
                'verbose_name': 'basket discount',
                'verbose_name_plural': 'basket discounts',
            },
        ),
    ]
