# Generated by Django 3.2.13 on 2022-05-13 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('discount', '0002_auto_20220512_1306'), ('discount', '0003_auto_20220513_0532'), ('discount', '0004_alter_discount_finish_at')]

    dependencies = [
        ('discount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='finish_at',
            field=models.DateTimeField(blank=True, default='', help_text='Discount finish date', verbose_name='finish at'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='start_at',
            field=models.DateTimeField(blank=True, default='', help_text='Discount start date', verbose_name='start at'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='finish_at',
            field=models.DateTimeField(default=None, help_text='Discount finish date', null=True, verbose_name='finish at'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='start_at',
            field=models.DateTimeField(help_text='Discount start date', verbose_name='start at'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='finish_at',
            field=models.DateTimeField(blank=True, default=None, help_text='Discount finish date', null=True, verbose_name='finish at'),
        ),
    ]
