# Generated by Django 3.2.13 on 2022-06-30 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0002_auto_20220512_1306_squashed_0004_alter_discount_finish_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='discount_type',
            field=models.CharField(choices=[('PD', 'Product discount'), ('BD', 'Basket discount')], default='PD', help_text='Discount type', max_length=2, verbose_name='discount type'),
        ),
    ]
