# Generated by Django 3.2.13 on 2022-04-27 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Delivery name', max_length=50, verbose_name='имя')),
                ('price', models.PositiveIntegerField(default=0, help_text='Delivery price', verbose_name='price')),
            ],
            options={
                'verbose_name': 'delivery',
                'verbose_name_plural': 'deliveries',
            },
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, help_text='Order date', verbose_name='order date')),
                ('payment', models.CharField(choices=[('card', 'Card'), ('some accounts', 'Some accounts')], help_text='Order payment', max_length=50, verbose_name='payment')),
                ('city', models.CharField(help_text='Order city', max_length=50, verbose_name='city')),
                ('address', models.CharField(help_text='Order address', max_length=250, verbose_name='address')),
                ('comment', models.TextField(help_text='Order comment', verbose_name='comment')),
                ('state', models.CharField(choices=[('paid', 'Paid'), ('not paid', 'Not paid'), ('delivered', 'Delivered'), ('received', 'Received')], help_text='Order state', max_length=50, verbose_name='state')),
                ('error', models.CharField(blank=True, choices=[('error1', 'Payment has not been completed, because you are suspected of intolerance'), ('error2', 'There are not enough funds in your account'), ('error3', 'Oops... Something went wrong')], help_text='Order error', max_length=250, verbose_name='error')),
                ('delivery_id', models.ForeignKey(help_text='Order delivery', null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.delivery', verbose_name='delivery')),
                ('user_id', models.ForeignKey(help_text='Order user', on_delete=django.db.models.deletion.CASCADE, related_name='order_info', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'info about order',
                'verbose_name_plural': 'info about orders',
                'ordering': ['-id'],
            },
        ),
    ]
