# Generated by Django 3.2.13 on 2022-04-27 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='comment',
            field=models.TextField(blank=True, help_text='Order comment', verbose_name='comment'),
        ),
    ]
