# Generated by Django 3.2.13 on 2022-04-28 08:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0002_alter_orderinfo_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderInfo',
            new_name='Order',
        ),
    ]
