# Generated by Django 3.2.13 on 2022-04-29 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_rename_orderinfo_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-id'], 'verbose_name': 'order', 'verbose_name_plural': 'orders'},
        ),
    ]
