# Generated by Django 3.2.13 on 2022-04-29 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_productreview_text'),
        ('order', '0004_alter_order_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_id',
            field=models.ForeignKey(help_text='Order delivery', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_delivery', to='order.delivery', verbose_name='delivery'),
        ),
        migrations.CreateModel(
            name='OrderEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(default=0, help_text='OrderEntity price', verbose_name='price')),
                ('count', models.PositiveIntegerField(default=0, help_text='OrderEntity count', verbose_name='count')),
                ('order_id', models.ForeignKey(help_text='OrderEntity order', on_delete=django.db.models.deletion.CASCADE, related_name='order_entity_order', to='order.order', verbose_name='order')),
                ('stock_id', models.ForeignKey(help_text='OrderEntity stock', on_delete=django.db.models.deletion.CASCADE, related_name='order_entity_stock', to='product.stock', verbose_name='stock')),
            ],
            options={
                'verbose_name': 'order entity',
                'verbose_name_plural': 'orders entity',
            },
        ),
    ]
