# Generated by Django 3.2.13 on 2022-05-01 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0008_alter_productreview_text'),
        ('order', '0005_auto_20220429_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0, help_text='Cart count', verbose_name='count')),
                ('stock_id', models.ForeignKey(help_text='Cart stock', on_delete=django.db.models.deletion.CASCADE, related_name='cart_stock', to='product.stock', verbose_name='stock')),
                ('user_id', models.ForeignKey(help_text='Cart user', on_delete=django.db.models.deletion.CASCADE, related_name='cart_user', to=settings.AUTH_USER_MODEL, verbose_name='cart')),
            ],
            options={
                'verbose_name': 'cart',
                'verbose_name_plural': 'carts',
                'ordering': ['-id'],
            },
        ),
    ]
