# Generated by Django 3.2.13 on 2022-05-04 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20220428_1940'),
        ('order', '0005_auto_20220429_1258'),
    ]

    operations = [
    ]
