# Generated by Django 3.2.13 on 2022-05-04 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('card', 'Card'), ('account', 'Some accounts')], help_text='Order payment', max_length=50, verbose_name='payment'),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('paid', 'Paid'), ('not paid', 'Not paid'), ('delivered', 'Delivered'), ('received', 'Received')], default='not paid', help_text='Order state', max_length=50, verbose_name='state'),
        ),
    ]
