# Generated by Django 3.2.13 on 2022-05-11 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_merge_0004_auto_20220428_1940_0005_auto_20220429_1258'),
        ('order', '0009_alter_orderentity_price_with_discount'),
    ]

    operations = [
    ]
