# Generated by Django 3.2.13 on 2022-05-15 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_merge_20220511_2024'),
        ('order', '0011_auto_20220511_1930'),
    ]

    operations = [
    ]
