# Generated by Django 3.2.13 on 2022-06-15 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_auto_20220524_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('card', 'Card'), ('account', 'Some accounts')], default='card', help_text='Order payment', max_length=50, verbose_name='payment type'),
        ),
    ]
