# Generated by Django 3.2.13 on 2022-06-16 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_auto_20220615_2252'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Delivery',
            new_name='DeliveryType',
        ),
    ]
