# Generated by Django 3.2.13 on 2022-06-16 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_rename_delivery_deliverytype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverytype',
            options={'verbose_name': 'delivery type', 'verbose_name_plural': 'delivery types'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
        migrations.AddField(
            model_name='deliverytype',
            name='cart_sum',
            field=models.PositiveIntegerField(default=0, help_text='Cart sum for special price', verbose_name='cart price'),
        ),
        migrations.AddField(
            model_name='deliverytype',
            name='special_price',
            field=models.PositiveIntegerField(default=0, help_text='Delivery special price', verbose_name='special price'),
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='', max_length=50)),
                ('address', models.TextField(default='')),
                ('price', models.DecimalField(decimal_places=2, default=200, max_digits=9)),
                ('delivery_type', models.ForeignKey(help_text='Delivery type', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_delivery_type', to='order.deliverytype', verbose_name='delivery_type')),
            ],
            options={
                'verbose_name': 'Delivery item',
                'verbose_name_plural': 'Delivery items',
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_id',
            field=models.ForeignKey(help_text='Order delivery', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_delivery', to='order.delivery', verbose_name='delivery'),
        ),
    ]
