# Generated by Django 3.2.13 on 2022-06-16 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_auto_20220616_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverytype',
            name='cart_sum',
            field=models.PositiveIntegerField(default=2000, help_text='Cart sum for special price', verbose_name='cart price'),
        ),
        migrations.AlterField(
            model_name='deliverytype',
            name='price',
            field=models.PositiveIntegerField(default=200, help_text='Delivery price', verbose_name='price'),
        ),
    ]
