# Generated by Django 3.2.13 on 2022-04-27 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('image', models.ImageField(upload_to='', verbose_name='image')),
                ('address', models.CharField(max_length=150, verbose_name='address')),
                ('phone', models.CharField(max_length=12, verbose_name='phone')),
                ('mobile', models.CharField(max_length=12, verbose_name='mobile')),
                ('email_general', models.EmailField(max_length=254, verbose_name='general email')),
                ('email_editor', models.EmailField(max_length=254, verbose_name='editor email')),
            ],
            options={
                'verbose_name': 'shop',
                'verbose_name_plural': 'shops',
                'ordering': ('name',),
            },
        ),
    ]
