# Generated by Django 3.2.13 on 2022-05-04 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='address',
            field=models.CharField(blank=True, max_length=150, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='email_editor',
            field=models.EmailField(blank=True, max_length=254, verbose_name='editor email'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='email_general',
            field=models.EmailField(blank=True, max_length=254, verbose_name='general email'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='image',
            field=models.ImageField(null=True, upload_to='shop_images/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='mobile',
            field=models.CharField(blank=True, max_length=12, verbose_name='mobile'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='phone',
            field=models.CharField(blank=True, max_length=12, verbose_name='phone'),
        ),
    ]
