# Generated by Django 3.2.13 on 2022-05-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20220504_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='quality_policy',
            field=models.CharField(blank=True, max_length=25, verbose_name='quality policy'),
        ),
        migrations.AddField(
            model_name='shop',
            name='refund_policy',
            field=models.CharField(blank=True, max_length=25, verbose_name='refund policy'),
        ),
        migrations.AddField(
            model_name='shop',
            name='shipping_policy',
            field=models.CharField(blank=True, max_length=25, verbose_name='shipping and returns policy'),
        ),
        migrations.AddField(
            model_name='shop',
            name='support_policy',
            field=models.CharField(blank=True, max_length=25, verbose_name='support policy'),
        ),
    ]
