# Generated by Django 3.2.13 on 2022-05-24 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20220520_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, verbose_name='mobile'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='phone'),
        ),
    ]
