# Generated by Django 3.2.13 on 2022-06-02 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_shop_image'),
        ('shop', '0005_auto_20220524_1235'),
    ]

    operations = [
    ]
