# Generated by Django 3.2.13 on 2022-06-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_merge_0005_alter_shop_image_0005_auto_20220524_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='image',
            field=models.ImageField(null=True, upload_to='shop_images/', verbose_name='image'),
        ),
    ]
