# Generated by Django 3.2.13 on 2022-06-08 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_shop_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='address_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='shop',
            name='address_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='shop',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='shop',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='shop',
            name='quality_policy_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='quality policy'),
        ),
        migrations.AddField(
            model_name='shop',
            name='quality_policy_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='quality policy'),
        ),
        migrations.AddField(
            model_name='shop',
            name='refund_policy_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='refund policy'),
        ),
        migrations.AddField(
            model_name='shop',
            name='refund_policy_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='refund policy'),
        ),
        migrations.AddField(
            model_name='shop',
            name='shipping_policy_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='shipping and returns policy'),
        ),
        migrations.AddField(
            model_name='shop',
            name='shipping_policy_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='shipping and returns policy'),
        ),
        migrations.AddField(
            model_name='shop',
            name='support_policy_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='support policy'),
        ),
        migrations.AddField(
            model_name='shop',
            name='support_policy_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='support policy'),
        ),
    ]
