# Generated by Django 3.2.13 on 2022-06-15 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20220609_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='name_ru',
        ),
    ]
