# Generated by Django 3.2.13 on 2022-04-27 13:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import user.utils


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('user', '0003_compare_view'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'пользователь', 'verbose_name_plural': 'пользователи'},
        ),
        migrations.AlterModelOptions(
            name='view',
            options={'ordering': ['-datetime'], 'verbose_name': 'view', 'verbose_name_plural': 'views'},
        ),
        migrations.AlterField(
            model_name='compare',
            name='product_id',
            field=models.ForeignKey(help_text='Product for comparison', on_delete=django.db.models.deletion.CASCADE, related_name='product_compare', to='product.product', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='compare',
            name='user_id',
            field=models.ForeignKey(help_text='A user who compares products', on_delete=django.db.models.deletion.CASCADE, related_name='user_compare', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, help_text='User avatar', upload_to=user.utils.avatar_directory_path, verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(help_text='User email', max_length=254, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(help_text='User first name', max_length=150, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(help_text='User last name', max_length=150, verbose_name='фамилия'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='middle_name',
            field=models.CharField(help_text='User middle name', max_length=150, verbose_name='middle name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(help_text='User phone', max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid format', regex='^\\+?1?\\d{8,15}$')], verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='view',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, help_text='Viewing datetime', verbose_name='datetime of addition'),
        ),
        migrations.AlterField(
            model_name='view',
            name='product_id',
            field=models.ForeignKey(help_text='Viewed product', on_delete=django.db.models.deletion.CASCADE, related_name='product_view', to='product.product', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='view',
            name='user_id',
            field=models.ForeignKey(help_text='The user who viewed the product', on_delete=django.db.models.deletion.CASCADE, related_name='user_view', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
    ]
