# Generated by Django 3.2.13 on 2022-04-28 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('user', '0004_auto_20220427_1622'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='View',
            new_name='UserProductView',
        ),
    ]
