# Generated by Django 3.2.13 on 2022-04-28 09:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_view_userproductview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, help_text='User phone', max_length=16, validators=[django.core.validators.RegexValidator(message='Invalid format', regex='^\\+?1?\\d{8,15}$')], verbose_name='phone'),
        ),
    ]
