# Generated by Django 3.2.13 on 2022-04-28 09:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(help_text='User phone', max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid format', regex='^\\+?1?\\d{8,15}$')], verbose_name='phone'),
        ),
    ]
