# Generated by Django 3.2.13 on 2022-04-28 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_customuser_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterField(
            model_name='compare',
            name='user_id',
            field=models.ForeignKey(help_text='A user who compares products', on_delete=django.db.models.deletion.CASCADE, related_name='user_compare', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(help_text='User first name', max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(help_text='User last name', max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='userproductview',
            name='user_id',
            field=models.ForeignKey(help_text='The user who viewed the product', on_delete=django.db.models.deletion.CASCADE, related_name='user_view', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
