# Generated by Django 3.2.13 on 2022-05-04 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20220428_1940'),
        ('user', '0009_auto_20220429_1102'),
    ]

    operations = [
    ]
