# Generated by Django 3.2.13 on 2022-05-11 16:34

from django.db import migrations, models
import user.utils


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, help_text='User avatar', upload_to=user.utils.avatar_directory_path, verbose_name='avatar'),
        ),
    ]
