# Generated by Django 3.2.13 on 2022-05-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20220527_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproductview',
            name='datetime',
            field=models.DateTimeField(auto_created=True, help_text='Viewing datetime', verbose_name='datetime of addition'),
        ),
    ]
