# Generated by Django 3.2.13 on 2022-05-30 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_alter_productreview_text'),
        ('user', '0018_alter_userproductview_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compare',
            name='product_id',
        ),
        migrations.AddField(
            model_name='compare',
            name='device',
            field=models.CharField(blank=True, help_text='cookie device value', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='compare',
            name='user_id',
            field=models.ForeignKey(blank=True, help_text='Compare user', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compare_user', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.CreateModel(
            name='CompareEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compare_entity', to='user.compare', verbose_name="compare's")),
                ('product', models.ForeignKey(help_text='Product for comparison', on_delete=django.db.models.deletion.CASCADE, related_name='product_compare', to='product.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'compare entity',
                'verbose_name_plural': 'compare entities',
            },
        ),
    ]
