# Generated by Django 3.2.13 on 2022-04-27 06:44

from django.db import migrations, models
import django.db.models.deletion
import product.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.BigIntegerField(default=None, help_text='Parent category id', null=True, verbose_name='parent id')),
                ('title', models.CharField(help_text='Category title', max_length=50, verbose_name='title')),
                ('icon', models.ImageField(default=None, help_text='Categiry icon', null=True, upload_to=product.utils.category_icon_path, verbose_name='icon')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Tag title', max_length=50, verbose_name='title')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Product  title', max_length=150, verbose_name='title')),
                ('image', models.ImageField(help_text='Product image', upload_to=product.utils.product_image_path, verbose_name='image')),
                ('short_description', models.CharField(help_text='Product short description', max_length=150, verbose_name='short description')),
                ('long_description', models.CharField(help_text='Product long description', max_length=150, verbose_name='long description')),
                ('is_limited', models.BooleanField(default=False, help_text='There is limited edition', verbose_name='is limited')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date the product was added', verbose_name='created at')),
                ('rating', models.PositiveSmallIntegerField(choices=[(0, 'Zero'), (1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')], default=0, help_text='Product rating', verbose_name='rating')),
                ('category_id', models.ForeignKey(help_text='Product category', on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product.category', verbose_name='category')),
                ('tag_id', models.ManyToManyField(blank=True, default='', related_name='product', to='product.Tag')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
    ]
