# Generated by Django 3.2.13 on 2022-04-28 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0002_auto_20220427_2358'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('text', models.TextField(default='', help_text='', max_length=1500, verbose_name='review content')),
                ('product', models.ForeignKey(help_text="Preview's product", on_delete=django.db.models.deletion.CASCADE, related_name='user_product_view', to='product.product', verbose_name='User product view product')),
                ('user', models.ForeignKey(help_text="Preview's user", on_delete=django.db.models.deletion.CASCADE, related_name='user_product_view', to=settings.AUTH_USER_MODEL, verbose_name='User product view user')),
            ],
            options={
                'verbose_name': 'user product view',
                'verbose_name_plural': 'user product views',
            },
        ),
        migrations.AddField(
            model_name='dailyoffer',
            name='text',
            field=models.TextField(default='', help_text='Daily offer promo content', max_length=1500, verbose_name='promo text'),
        ),
        migrations.DeleteModel(
            name='UserProductView',
        ),
    ]
