# Generated by Django 3.2.13 on 2022-05-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20220513_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sort_index',
            field=models.SmallIntegerField(default=0, help_text='Sort index', verbose_name='sort index'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='text',
            field=models.TextField(default='', help_text='', max_length=1500, verbose_name='review content'),
        ),
    ]
