# Generated by Django 3.2.13 on 2022-05-15 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20220514_0934'),
        ('product', '0017_alter_productreview_text'),
    ]

    operations = [
    ]
