# Generated by Django 3.2.13 on 2022-05-21 10:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import product.utils


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_alter_productreview_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=8, verbose_name='unit')),
                ('unit_description', models.CharField(max_length=128, verbose_name='unit description')),
            ],
        ),
        migrations.AddField(
            model_name='attribute',
            name='rank',
            field=models.IntegerField(default=0, help_text='Rank of importance. 100 - most important', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='product_item', to='product.product', verbose_name='product item'),
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_attribute', to='product.attribute', verbose_name="product's attribute"),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='text',
            field=models.TextField(default='', help_text='', max_length=1500, verbose_name='review content'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Product image', upload_to=product.utils.product_image_path, verbose_name='image')),
                ('product', models.ForeignKey(help_text='Product image', on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product.product', verbose_name='product of image')),
            ],
            options={
                'verbose_name': 'product image',
                'verbose_name_plural': 'product images',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='unit',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='value_unit', to='product.unit', verbose_name='unit'),
        ),
    ]
