# Generated by Django 3.2.13 on 2022-06-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_alter_productreview_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, default=1, help_text='Product rating', verbose_name='rating'),
            preserve_default=False,
        ),
    ]
