# Generated by Django 3.2.13 on 2022-05-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_attribute_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributevalue',
            name='value',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='value'),
        ),
    ]
