# Generated by Django 3.2.13 on 2022-06-06 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_alter_attributevalue_value'),
        ('product', '0028_alter_productreview_rating'),
    ]

    operations = [
    ]
