# Generated by Django 3.2.13 on 2022-06-09 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_auto_20220608_1203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'verbose_name': 'unit', 'verbose_name_plural': 'units'},
        ),
    ]
