# Generated by Django 3.2.13 on 2022-06-21 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_alter_unit_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyoffer',
            name='text',
            field=models.TextField(blank=True, default='', help_text='Daily offer promo content', max_length=1500, verbose_name='promo text'),
        ),
    ]
