# Generated by Django 3.2.13 on 2022-06-30 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_alter_dailyoffer_text'),
        ('product', '0032_auto_20220620_2122'),
    ]

    operations = [
    ]
