# Generated by Django 3.2.13 on 2022-06-30 17:46

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_merge_20220630_2035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productreview',
            options={'verbose_name': "user's review", 'verbose_name_plural': "user's review"},
        ),
        migrations.AlterModelManagers(
            name='category',
            managers=[
                ('admin_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='attribute',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute', to='product.category', verbose_name="'attribute's category'"),
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_attribute', to='product.attribute', verbose_name="'product's attribute'"),
        ),
        migrations.AlterField(
            model_name='dailyoffer',
            name='text',
            field=models.TextField(default='', help_text='Daily offer promo content', max_length=1500, verbose_name='promo text'),
        ),
    ]
