# Generated by Django 3.2.13 on 2022-07-17 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import product.utils


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20220630_2046'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0034_auto_20220630_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='type',
            field=models.CharField(choices=[('T', 'text'), ('C', 'check'), ('S', 'select')], default='T', help_text='field type', max_length=1, verbose_name='field type'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(default=None, help_text='category icon', null=True, upload_to=product.utils.category_icon_path, verbose_name='icon'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, help_text='parent category', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='product.category', verbose_name='parent id'),
        ),
        migrations.AlterField(
            model_name='category',
            name='sort_index',
            field=models.SmallIntegerField(default=0, help_text='sort index', verbose_name='sort index'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(help_text='category title', max_length=50, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title_en',
            field=models.CharField(help_text='category title', max_length=50, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title_ru',
            field=models.CharField(help_text='category title', max_length=50, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='dailyoffer',
            name='product',
            field=models.ForeignKey(help_text="daily's offer product", on_delete=django.db.models.deletion.CASCADE, related_name='daily_offer', to='product.product', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='dailyoffer',
            name='text',
            field=models.TextField(default='', help_text='daily offer promo content', max_length=1500, verbose_name='promo text'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(help_text='product category', on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product.category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='date the product was added', verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='product image', upload_to=product.utils.product_image_path, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_limited',
            field=models.BooleanField(default=False, help_text='there is limited edition', verbose_name='is limited'),
        ),
        migrations.AlterField(
            model_name='product',
            name='long_description',
            field=models.TextField(help_text='product long description', max_length=1500, verbose_name='long description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='long_description_en',
            field=models.TextField(help_text='product long description', max_length=1500, null=True, verbose_name='long description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='long_description_ru',
            field=models.TextField(help_text='product long description', max_length=1500, null=True, verbose_name='long description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Zero'), (1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')], default=0, help_text='product rating', verbose_name='rating'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.CharField(help_text='product short description', max_length=150, verbose_name='short description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description_en',
            field=models.CharField(help_text='product short description', max_length=150, null=True, verbose_name='short description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description_ru',
            field=models.CharField(help_text='product short description', max_length=150, null=True, verbose_name='short description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sort_index',
            field=models.SmallIntegerField(default=0, help_text='sort index', verbose_name='sort index'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(help_text='product title', max_length=150, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title_en',
            field=models.CharField(help_text='product title', max_length=150, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title_ru',
            field=models.CharField(help_text='product title', max_length=150, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, help_text='product image', upload_to=product.utils.product_image_path, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(help_text='product image', on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product.product', verbose_name='product of image'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='product',
            field=models.ForeignKey(help_text="preview's product", on_delete=django.db.models.deletion.CASCADE, related_name='user_product_view', to='product.product', verbose_name='user product view product'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='product rating', verbose_name='rating'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='text',
            field=models.TextField(default='', help_text='review content', max_length=1500, verbose_name='review content'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='user',
            field=models.ForeignKey(help_text="preview's user", on_delete=django.db.models.deletion.CASCADE, related_name='user_product_view', to=settings.AUTH_USER_MODEL, verbose_name='user product view user'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='product',
            field=models.ForeignKey(help_text="stock's product", on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='product.product', verbose_name='product id'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='shop',
            field=models.ForeignKey(help_text="stock's shop", on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='shop.shop', verbose_name='shop id'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(help_text='tag title', max_length=50, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title_en',
            field=models.CharField(help_text='tag title', max_length=50, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title_ru',
            field=models.CharField(help_text='tag title', max_length=50, null=True, verbose_name='title'),
        ),
    ]
