# Generated by Django 3.2.13 on 2022-05-12 09:01

from django.db import migrations, models
import info.utils


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(help_text='Banner image', upload_to=info.utils.banner_image_path, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='is_active',
            field=models.BooleanField(help_text='Banner is active', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='text',
            field=models.TextField(help_text='Banner text', verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(help_text='Banner title', max_length=150, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='url',
            field=models.URLField(help_text='Banner url', verbose_name='URL'),
        ),
    ]
