# Generated by Django 3.2.13 on 2022-05-12 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20220512_1201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ('is_active',), 'verbose_name': 'banner', 'verbose_name_plural': 'banners'},
        ),
    ]
