# Generated by Django 3.2.13 on 2022-05-23 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_alter_banner_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seoitem',
            name='meta_description',
            field=models.CharField(blank=True, help_text='For detail pages (products, shop etc) after meta descriptionauto adding description field of detail page', max_length=512, verbose_name='meta description'),
        ),
        migrations.AlterField(
            model_name='seoitem',
            name='meta_title',
            field=models.CharField(help_text='For detail pages (products, shop etc) after meta titleauto adding name (title) field of detail page', max_length=512, verbose_name='meta title'),
        ),
    ]
