# Generated by Django 3.2.13 on 2022-05-25 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_auto_20220524_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='description',
            field=models.CharField(max_length=250, verbose_name='description'),
        ),
    ]
