<<<<<<< HEAD
# Generated by Django 3.2.13 on 2022-06-07 16:48
=======
# Generated by Django 3.2.13 on 2022-06-08 06:44
>>>>>>> 0db8b9fd360c4d7c9ba50a92c2ccf480ac0bd4e7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_alter_settings_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seoitem',
            name='meta_description',
            field=models.CharField(blank=True, help_text='For detail pages (products, shop etc)after meta descriptionauto adding description field of detail page', max_length=512, verbose_name='meta description'),
        ),
    ]
