# Generated by Django 3.2.13 on 2022-06-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_alter_seoitem_meta_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='text_en',
            field=models.TextField(help_text='Banner text', null=True, verbose_name='text'),
        ),
        migrations.AddField(
            model_name='banner',
            name='text_ru',
            field=models.TextField(help_text='Banner text', null=True, verbose_name='text'),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_en',
            field=models.CharField(help_text='Banner title', max_length=150, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_ru',
            field=models.CharField(help_text='Banner title', max_length=150, null=True, verbose_name='title'),
        ),
    ]
