# Generated by Django 3.2.13 on 2022-06-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_auto_20220608_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='seoitem',
            name='meta_description_en',
            field=models.CharField(blank=True, help_text='For detail pages (products, shop etc)after meta descriptionauto adding description field of detail page', max_length=512, null=True, verbose_name='meta description'),
        ),
        migrations.AddField(
            model_name='seoitem',
            name='meta_description_ru',
            field=models.CharField(blank=True, help_text='For detail pages (products, shop etc)after meta descriptionauto adding description field of detail page', max_length=512, null=True, verbose_name='meta description'),
        ),
        migrations.AddField(
            model_name='seoitem',
            name='meta_title_en',
            field=models.CharField(help_text='For detail pages (products, shop etc) after meta titleauto adding name (title) field of detail page', max_length=512, null=True, verbose_name='meta title'),
        ),
        migrations.AddField(
            model_name='seoitem',
            name='meta_title_ru',
            field=models.CharField(help_text='For detail pages (products, shop etc) after meta titleauto adding name (title) field of detail page', max_length=512, null=True, verbose_name='meta title'),
        ),
    ]
