# Generated by Django 3.2.13 on 2022-06-15 22:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0016_auto_20220615_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('card', models.CharField(max_length=9, verbose_name='card number')),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('canceled', 'Canceled'), ('success', 'Success'), ('error', 'Error')], default='processing', max_length=150, verbose_name='status')),
                ('message', models.CharField(blank=True, max_length=255, verbose_name='message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='order.order', unique=True, verbose_name='order')),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
                'ordering': ('order', 'created_at'),
            },
        ),
    ]
